version: '3.8'
services:
  node-api:
    build: ./nodejs-api
    command: nodemon -L server/index.js
    container_name: nodejs-api_container
    ports:
      - 5000:8080
    restart: always
    links:
      - mongo
    volumes:
      - ./nodejs-api:/app
  react-app:
    build: ./display-api-react
    environment:
      # - CHOKIDAR_USEPOLLING=true # create-ui-app <= 5.x
      - WATCHPACK_POLLING=true # create-ui-app >= 5.x
    container_name: react-app_container
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./display-api-react:/app
  mongo:
    image: mongo:6.0.2-focal
    container_name: mongo_container
    ports:
      - 27012:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=api_db_user
      - MONGO_INITDB_ROOT_PASSWORD=api_db_passXYZ
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: {}